name: Andriod APK Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build app APK
        run: |
          bash ./gradlew -PappVerName=${{ env.VERSION }} assembleRelease
          bash ./gradlew assembleDebug
        
      - name: Sign app APK
        if: success()
        id: sign
        uses: r0adkll/sign-android-release@v1
        env:
          BUILD_TOOLS_VERSION: "31.0.0"
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          
      - name: Upload Release APK
        uses: actions/upload-artifact@v2
        with:
          name: MiuiHome_release
          path: "app/build/outputs/apk/release/*-signed.apk"
          
      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: MiuiHome_debug
          path: "app/build/outputs/apk/debug/*.apk"
          
      - name: Post to channel
        if: contains(github.event.head_commit.message, '[skip post]') == false
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          export Release="app/build/outputs/apk/release/*-signed.apk"
          export Debug="app/build/outputs/apk/debug/*.apk"
          ESCAPED=`python3 -c 'import json,os,urllib.parse; msg = json.dumps(os.environ["COMMIT_MESSAGE"]); print(urllib.parse.quote(msg if len(msg) <= 1024 else json.dumps(os.environ["COMMIT_URL"])))'`
          curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${CHANNEL_ID}&media=%5B%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2FriruRelease%22%7D%2C%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2FzygiskRelease%22%7D%2C%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2FriruDebug%22%7D%2C%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2FzygiskDebug%22%2C%22caption%22:${ESCAPED}%7D%5D" -F release="@$Release" -F debug="@$Debug"
