name: Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Build with Gradle
        run: chmod +x gradlew && bash ./gradlew assembleDebug

      - name: Sign Android release
        if: success()
        id: sign
        uses: r0adkll/sign-android-release@v1
        env:
          BUILD_TOOLS_VERSION: "31.0.0"
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Debud APK
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.buildRelease.outputs.debugName }}_debug
          path: app/build/outputs/apk/debug/*.apk
  
