name: Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Build with Gradle
        run: chmod +x gradlew && bash ./gradlew assembleDebug
        
      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.buildRelease.outputs.debugName }}_debug
          path: app/build/outputs/apk/debug/*.apk
  
